wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 1d
  ap:
    ssid: $devicename" AP"
    password: !secret ap_wifi_password

captive_portal:

ota:
 password: !secret ota_password

