esphome:
  name: $devicename

esp32:
  board: ttgo-lora32-v21
  framework:
    type: arduino


logger:
  logs:
    mqtt.component: INFO
    mqtt.client: INFO
    component: ERROR
# mqtt:
#   broker: 10.0.9.99
#   username: !secret mqtt_user
#   password: !secret mqtt_pass
#   discovery: true

web_server:
  port: 80

#Enable Home Assistant API
api:
 # password: !secret ha_api_password

i2c:   # for OLED display
  sda: 21 
  scl: 22




