wifi_ssid: io
wifi_password: nostromo
ap_wifi_password: nostromo
ha_api_password: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkNjMxMDcwN2FmZDY0ZWYzODJlYmNlZjQyZmZmOTE2MyIsImlhdCI6MTY2NzM0NTg3OCwiZXhwIjoxOTgyNzA1ODc4fQ.0P-XLHVa780w5D5LAd8g50jbLFFJJq_qYsOAj9uI7XU
ota_password: nostromo
logging_syslog_collector_ip: 10.0.9.99
web_username: idimou
web_password: nostromo
mqtt_user: cedalo
mqtt_pass: fUno0zlGDj